import CtaBox from "../components/CtaBox1";
import Header from "../components/Header";
import TitleAreaCenter from "../components/TitleAreaCenter";
import IbAnimation from "../components/animations/IbAnimation";
import { Link } from "react-router-dom";

function IntroducingBroker() {
  const breadcrumbPaths = [
    { name: "Home", href: "/" },
    { name: "Partners", href: "" },
    { name: "Introducing Broker" },
  ];
  return (
    <>
      <Header mode={"light"} />
      <TitleAreaCenter
        title="Introducing Broker"
        description="Earn 75% of our revenue. At Fastone Markets, we believe in rewarding our partners generously. Our Introducing Broker Program is designed to offer you the opportunity to earn a significant portion of the revenue generated by the traders you refer. The more they trade, the more you earn!"
        breadcrumbPaths={breadcrumbPaths}
      />
      <section className="wc-fmarket wc-fm-2">
        <div className="container">
        <div className="row partner-img-1 justify-content-center mb-4">
            <a
              href="/docs/Fastone Global Markets IB Program.pdf"
              target="_blank"
              rel="noopener noreferrer"
              className="animated-pdf-btn"
            >
              Download IB Program PDF
            </a>
          </div>
          <div className="row partner-img-1">
            <IbAnimation />
          </div>
          <div className="row">
            <div className="col-md-4">
              <div className="wcfm-col">
                <p>
                  Partner with FastOne Markets - where your referrals lead to
                  real rewards. Enjoy high commissions and support at every
                  step.
                </p>
              </div>
            </div>
            <div className="col-md-4">
              <div className="wcfm-col">
                <p>
                  Maximize your earnings while offering top-tier
                  trading conditions.
                </p>
              </div>
            </div>
            <div className="col-md-4">
              <div className="wcfm-col">
                <p>
                  Join FastOne Markets' IB program and enjoy best earning programs and per lot commissions.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="inf-cta">
        <div className="container">
          <div className="row inf-cta-title">
            <div className="col-md-5">
              <h2 className="wcu-title">
                Interested in IB Partnership opportunities??
              </h2>
            </div>
            <div className="col-md-7 af-border">
              <p>
                Join our IB Program today and elevate your business with
                our unparalleled support and resources. Experience the benefits
                of partnering with a leading CFD provider and watch your success
                grow!
              </p>
            </div>
          </div>
          <div className="row reg-steps">
            <div className="col-md-4">
              <img
                src="/images/icons/register.png"
                alt=""
                className="inf-icon"
              />
              <h3>1. Register</h3>
              <p>
                Fill out a simple application form, and we'll review it on the
                same day.
              </p>
            </div>
            <div className="col-md-4">
              <img src="/images/icons/refer.png" alt="" className="inf-icon" />
              <h3>2. Refer</h3>
              <p>
                After signing up, you'll receive a tracking link that gives you
                access to our marketing and operational tools.
              </p>
            </div>
            <div className="col-md-4">
              <img
                src="/images/icons/earn-reward.png"
                alt=""
                className="inf-icon"
              />
              <h3>3. Earn Rewards</h3>
              <p>
                Send us your leads, and you'll start earning as soon as they
                begin trading.
              </p>
            </div>
          </div>
          <div className="inf-cta-btn">
            <a className="btn-one rounded-btn inf-account" href="https://my.fastoneglobalmarkets.co/en/register">
              Create your Partner Account
            </a>
          </div>
        </div>
      </section>

      <section className="about-notes">
        <div className="container abt-margin-2">
          <div className="row">
            <div className="col-md-4 card about-br">
              <h3>Refer Traders</h3>
              <p>
                Simply introduce traders to Fastone Markets. Once they open an
                account and start trading, your earnings begin.
              </p>
            </div>
            <div className="col-md-4 card about-br">
              <h3>Earn as They Trade</h3>
              <p>
                You earn up to 75% of the revenue generated by each active
                trader you refer. This revenue comes from the trading fees,
                spreads, and commissions that Fastone Markets collects from
                their trading activities.
              </p>
            </div>
            <div className="col-md-4 card">
              <h3>Continuous Income</h3>
              <p>
                As long as your referred traders remain active, your income
                continues. The more they trade, the more you earn.
              </p>
            </div>
          </div>
        </div>
      </section>

      <section className="wc-fmarket">
        <div className="container">
          <h2>Why Choose Fastone Markets?</h2>
          <div className="row">
            <div className="col-md-6">
              <div className="wcfm-col">
                <h3>High Payouts</h3>
                <p>
                  With a revenue share of up to 75%, we offer one of the most
                  competitive IB programs in the industry.
                </p>
              </div>
            </div>
            <div className="col-md-6">
              <div className="wcfm-col">
                <h3>Advanced Trading Platform</h3>
                <p>
                  Your clients will have access to cutting-edge trading
                  technology, ensuring they have the best tools to succeed.
                </p>
              </div>
            </div>
            <div className="col-md-6">
              <div className="wcfm-col">
                <h3>Comprehensive Support</h3>
                <p>
                  We provide full support to help you grow your business,
                  including marketing materials, dedicated account managers, and
                  regular performance reports.
                </p>
              </div>
            </div>
            <div className="col-md-6">
              <div className="wcfm-col">
                <h3>Transparent Reporting</h3>
                <p>
                  Stay updated with detailed reports that track your referrals
                  and earnings in real-time.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="ib-cta">
        <div className="container">
          <div className="row justify-content-center text-center">
            <div className="col-md-12">
              <h2 className="display-4">Join Our Network of Successful IBs</h2>
              <p className="lead px-lg-12 m-5">
                Become a part of Fastone Markets' growing community of
                Introducing Brokers and start earning today. Whether you’re an
                individual or a company, our program is designed to help you
                succeed.
              </p>
              <div className="d-flex justify-content-center">
                <a href="https://my.fastoneglobalmarkets.co/en/register" className="btn-one rounded-btn white-btn">
                  Partner with us
                </a>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="ib-mktp">
        <div className="container">
          <div className="row">
            <div>
              <div className="text-center mb-lg-10 mb-6">
                <h2>Why partner with Fastone Markets?</h2>
                <p className="lead m-4">
                  Lucrative Commission Structure: Ensuring consistent and
                  substantial revenue, regardless of market conditions.
                </p>
              </div>
            </div>
          </div>
          <div className=" row mt-5">
            <div className="col-md-12">
              <div className="row mkt-feat">
                <div className="col-md-6">
                  <div className="card-st-2">
                    <h4>Same-Day Deposits and Withdrawals</h4>
                    <p>
                      Offer your clients the convenience of same-day deposits
                      and withdrawals, enhancing their trading experience and
                      trust in your partnership.
                    </p>
                  </div>
                </div>
                <div className="col-md-6">
                  <div className="card-st-2">
                    <h4>Comprehensive Support</h4>
                    <p>
                      Partner with a leading CFD provider that offers full
                      marketing, technical, and client support, empowering you
                      to focus on growing your business.
                    </p>
                  </div>
                </div>
                <div className="col-md-6">
                  <div className="card-st-2">
                    <h4>Client Education Programs</h4>
                    <p>
                      Provide your clients with access to comprehensive
                      educational resources, including webinars, tutorials, and
                      trading guides, to enhance their trading skills and
                      knowledge.
                    </p>
                  </div>
                </div>
                <div className="col-md-6">
                  <div className="card-st-2">
                    <h4>Daily Market Technical and Fundamental Support</h4>
                    <p>
                      Equip your clients with daily market analysis, technical
                      insights, and fundamental updates to help them make
                      informed trading decisions.
                    </p>
                  </div>
                </div>
                <div className="col-md-6">
                  <div className="card-st-2">
                    <h4>Advanced Trading Environment</h4>
                    <p>
                      Offer your clients top-tier trading tools, competitive
                      spreads, and high leverage up to 1:500, making FastOne
                      Markets a preferred choice for serious traders.
                    </p>
                  </div>
                </div>
                <div className="col-md-6">
                  <div className="card-st-2">
                    <h4>Diverse Asset Offering</h4>
                    <p>
                      Attract more clients by offering a wide range of trading
                      instruments, including forex, precious metals, and CFDs,
                      all on a single platform.
                    </p>
                  </div>
                </div>
                <div className="col-md-6">
                  <div className="card-st-2">
                    <h4>Reputation and Reliability</h4>
                    <p>
                      Benefit from our strong market presence, robust security
                      measures, and commitment to transparency, making FastOne
                      Markets a trusted partner in the financial industry.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
  
      <CtaBox
        heading="Still confused which partnership to choose ?"
        description="Talk to our partnership expert now!"
        buttonText="Live Chat"
        buttonImage="/images/icons/chat.png"
        sectionColor=""
      />
    </>
  );
}

export default IntroducingBroker;
